### PR TITLE
added steps in the blank space of the first page

### LINKED ISSUE #4: Add steps/ guide to use website
Add short steps in below blank space, describing steps of procedure to use the website with URL example

Preview:

issue4

### PR DESCRIPTION
**Pull request by VedVaghela**
Fixes #4

### CODE REVIEW

**Review by kartik3805 — APPROVED** [review]
Great! everything looks fine

**Comment by kartik3805** [comment]
Resolve the conflict and hide all steps when content gets fetched

**Comment by VedVaghela** [comment]
> Resolve the conflict and hide all steps when content gets fetched

yes will do it

**Comment by kartik3805** [comment]
Yes you can make new pull request

**Comment by kartik3805** [comment]
Issue fixed

**Pull request closed without merging**
