### PR TITLE
Fixes #6

### LINKED ISSUE #6: Front end issue
image
Found design issues, would like to fix it.
- Extra white space 
- 'Get quick and short summary for your desired wikipedia article' can be removed when results are given
- Page URL not alinged properly

### PR DESCRIPTION
**Pull request by dharmikjethva30**
Fixes #6

### CODE REVIEW

**Comment by kartik3805** [comment]
Make short description and page URL as it was before 

issue6

**Comment by dharmikjethva30** [comment]
> Make short description and page URL as it was before
> 
> issue6

doesnt this look better?
if you want i can make it as it was

**Comment by dharmikjethva30** [comment]
please check my updated commit !
Open to suggestion

**Comment by kartik3805** [comment]
Sorry but UI changes are not going overall website theme

**Pull request closed without merging**
