### PR TITLE
Submit button responsive and styles added

### PR DESCRIPTION
**Pull request by rubenfreiria**

### CODE REVIEW

**Comment by rubenfreiria** [comment]
image

**Comment by kartik3805** [comment]
Can you increase its width so that it can cover 90% of screen width

**Comment by rubenfreiria** [comment]
image
Pls, check it. I think that now works well.

**Comment by kartik3805** [comment]
Now in desktop version also width got increased, you can apply all the CSS changes to 
[ @media only screen and (max-width: 600px)  ], which is in the last of CSS file

issue7

**Comment by rubenfreiria** [comment]
image
image

Thanks, I have learned how @media works.

**Comment by kartik3805** [comment]
Issue fixed by another contributor

**Pull request closed without merging**
